"""Initial migration

Revision ID: 156130a79284
Revises: 
Create Date: 2025-08-02 05:03:56.577330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156130a79284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('campaign_jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('make_scenario_id', sa.String(length=100), nullable=True),
    sa.Column('job_parameters', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('campaign_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_jobs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_jobs_job_name'), ['job_name'], unique=True)

    op.create_table('campaigns',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('job_webhook_url', sa.String(length=500), nullable=False),
    sa.Column('campaign_description', sa.Text(), nullable=True),
    sa.Column('selected_contacts', sa.Text(), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=False),
    sa.Column('processed_contacts', sa.Integer(), nullable=True),
    sa.Column('successful_contacts', sa.Integer(), nullable=True),
    sa.Column('failed_contacts', sa.Integer(), nullable=True),
    sa.Column('campaign_status', sa.Enum('draft', 'running', 'completed', 'failed', 'paused', name='campaign_status_enum'), nullable=True),
    sa.Column('execution_start_time', sa.DateTime(), nullable=True),
    sa.Column('execution_end_time', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('campaign_settings', sa.Text(), nullable=True),
    sa.Column('make_scenario_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_campaign_status'), ['campaign_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_job_name'), ['job_name'], unique=False)

    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('validation_status', sa.Enum('pending', 'valid', 'invalid', 'duplicate', name='validation_status_enum'), nullable=True),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('email_verification_status', sa.Enum('not_verified', 'valid', 'invalid', 'risky', 'unknown', name='email_verification_status_enum'), nullable=True),
    sa.Column('email_verification_date', sa.DateTime(), nullable=True),
    sa.Column('email_verification_details', sa.Text(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_field1', sa.String(length=255), nullable=True),
    sa.Column('custom_field2', sa.String(length=255), nullable=True),
    sa.Column('custom_field3', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_email_address'), ['email_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email_verification_status'), ['email_verification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_upload_batch_id'), ['upload_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_validation_status'), ['validation_status'], unique=False)

    op.create_table('upload_batches',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('valid_records', sa.Integer(), nullable=True),
    sa.Column('invalid_records', sa.Integer(), nullable=True),
    sa.Column('duplicate_records', sa.Integer(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.Enum('uploading', 'processing', 'completed', 'failed', name='processing_status_enum'), nullable=True),
    sa.Column('processing_errors', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('validation_rules_applied', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_batches_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_batches_upload_timestamp'), ['upload_timestamp'], unique=False)

    op.create_table('validation_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.Enum('required_field', 'format_validation', 'custom_logic', name='rule_type_enum'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('validation_pattern', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rule_order', sa.Integer(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    with op.batch_alter_table('validation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_rules_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_rules_rule_type'), ['rule_type'], unique=False)

    op.create_table('webhook_configs',
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('webhook_type', sa.String(length=255), nullable=False),
    sa.Column('input_fields', sa.Text(), nullable=True),
    sa.Column('output_fields', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('header_name', sa.String(length=100), nullable=True),
    sa.Column('header_value', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('webhook_id')
    )
    op.create_table('campaign_executions',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('contact_ids', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='campaign_execution_status_enum'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('completed_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['campaign_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('campaign_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_executions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_executions_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_executions_status'), ['status'], unique=False)

    op.create_table('campaign_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'sent', 'delivered', 'failed', 'bounced', name='processing_status_enum'), nullable=True),
    sa.Column('make_response', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sample_requested', sa.Boolean(), nullable=True),
    sa.Column('processed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('delivery_timestamp', sa.DateTime(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    with op.batch_alter_table('campaign_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_results_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_results_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_results_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_results_sample_requested'), ['sample_requested'], unique=False)

    op.create_table('verification_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('contact_ids', sa.Text(), nullable=True),
    sa.Column('webhook_config_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='verification_job_status_enum'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('completed_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_config_id'], ['webhook_configs.webhook_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('verification_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_jobs_status'), ['status'], unique=False)

    op.create_table('sample_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('fulfillment_status', sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='fulfillment_status_enum'), nullable=True),
    sa.Column('fulfillment_notes', sa.Text(), nullable=True),
    sa.Column('shipped_date', sa.DateTime(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('shipping_carrier', sa.String(length=50), nullable=True),
    sa.Column('fulfilled_by', sa.String(length=100), nullable=True),
    sa.Column('fulfillment_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('quantity_requested', sa.Integer(), nullable=True),
    sa.Column('quantity_shipped', sa.Integer(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['campaign_results.result_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('sample_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_requests_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_requests_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_requests_fulfillment_status'), ['fulfillment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_requests_shipped_date'), ['shipped_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_requests_shipped_date'))
        batch_op.drop_index(batch_op.f('ix_sample_requests_fulfillment_status'))
        batch_op.drop_index(batch_op.f('ix_sample_requests_contact_id'))
        batch_op.drop_index(batch_op.f('ix_sample_requests_campaign_id'))

    op.drop_table('sample_requests')
    with op.batch_alter_table('verification_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_jobs_status'))

    op.drop_table('verification_jobs')
    with op.batch_alter_table('campaign_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_results_sample_requested'))
        batch_op.drop_index(batch_op.f('ix_campaign_results_processing_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_results_contact_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_results_campaign_id'))

    op.drop_table('campaign_results')
    with op.batch_alter_table('campaign_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_executions_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_executions_job_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_executions_campaign_id'))

    op.drop_table('campaign_executions')
    op.drop_table('webhook_configs')
    with op.batch_alter_table('validation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_rules_rule_type'))
        batch_op.drop_index(batch_op.f('ix_validation_rules_is_active'))
        batch_op.drop_index(batch_op.f('ix_validation_rules_field_name'))

    op.drop_table('validation_rules')
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_batches_upload_timestamp'))
        batch_op.drop_index(batch_op.f('ix_upload_batches_processing_status'))

    op.drop_table('upload_batches')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_validation_status'))
        batch_op.drop_index(batch_op.f('ix_contacts_upload_batch_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_email_verification_status'))
        batch_op.drop_index(batch_op.f('ix_contacts_email_address'))

    op.drop_table('contacts')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_job_name'))
        batch_op.drop_index(batch_op.f('ix_campaigns_created_by'))
        batch_op.drop_index(batch_op.f('ix_campaigns_campaign_status'))

    op.drop_table('campaigns')
    with op.batch_alter_table('campaign_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_jobs_job_name'))
        batch_op.drop_index(batch_op.f('ix_campaign_jobs_is_active'))

    op.drop_table('campaign_jobs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action_type'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
