"""Add headers column to webhook_configs

Revision ID: 9c2d585d6ce4
Revises:
Create Date: 2025-07-28 18:45:07.025886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2d585d6ce4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headers', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.drop_column('headers')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('row_number')

    # ### end Alembic commands ###
