"""Add headers to campaign_jobs

Revision ID: b1b2c3d4e5f6
Revises: 9c2d585d6ce4
Create Date: 2025-07-28 21:41:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b2c3d4e5f6'
down_revision = '9c2d585d6ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headers', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_jobs', schema=None) as batch_op:
        batch_op.drop_column('headers')

    # ### end Alembic commands ###
