"""Add headers field to webhook config

Revision ID: fbeade635cb4
Revises: 
Create Date: 2025-07-31 13:51:03.760878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbeade635cb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.drop_column('header_name')
        batch_op.drop_column('header_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_value', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('header_name', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
